### ISSUE TITLE
'already_running' shown when trying to run more than one instance, even of different version

### ISSUE THREAD

**Issue by philstopford** [CineEncoder/CineEncoder#44]
I tried to launch the development code whilst having the stable release also running and got this complaint; I also see it for trying to run two instances of the same version.

It would be useful to be able to run two instances because adding jobs in batch mode isn't possible whilst the tool is running. Alternatively, being able to work in the GUI whilst the tool is running would be neat.

**Comment by CineEncoder** [comment]
Hello!
I can add this option in the settings so that the user can choose whether to run the program in multiple instances.
The possibility of batch mode has already been added, there is a single/batch switch at the bottom of the central dock.
Over time, it will also be possible to modify so that the interface is not blocked or partially blocked.

**Comment by philstopford** [comment]
This works nicely. Thank you!
